// <auto-generated />
using System;
using GovAmbiental.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovAmbiental.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GovAmbiental.API.Models.AcaoCorretiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NaoConformidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrazoLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NaoConformidadeId")
                        .IsUnique();

                    b.HasIndex("Status", "PrazoLimite");

                    b.ToTable("AcoesCorretivas");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("ScoreConformidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadeOperacional")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("DataInicio");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "UnidadeOperacional");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.ItemAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendido")
                        .HasColumnType("bit");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequisitoNormaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoNormaId");

                    b.HasIndex("AuditoriaId", "RequisitoNormaId")
                        .IsUnique();

                    b.ToTable("ItensAuditoria");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.NaoConformidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("IdentificadaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequisitoNormaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriaId");

                    b.HasIndex("RequisitoNormaId");

                    b.ToTable("NaoConformidades");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.NormaAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ativa", "Categoria");

                    b.ToTable("Normas");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.RequisitoNorma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NormaAmbientalId")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormaAmbientalId");

                    b.ToTable("Requisitos");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.AcaoCorretiva", b =>
                {
                    b.HasOne("GovAmbiental.API.Models.NaoConformidade", "NaoConformidade")
                        .WithOne("AcaoCorretiva")
                        .HasForeignKey("GovAmbiental.API.Models.AcaoCorretiva", "NaoConformidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NaoConformidade");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.ItemAuditoria", b =>
                {
                    b.HasOne("GovAmbiental.API.Models.Auditoria", "Auditoria")
                        .WithMany("Itens")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovAmbiental.API.Models.RequisitoNorma", "Requisito")
                        .WithMany("Itens")
                        .HasForeignKey("RequisitoNormaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Requisito");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.NaoConformidade", b =>
                {
                    b.HasOne("GovAmbiental.API.Models.Auditoria", "Auditoria")
                        .WithMany("NaoConformidades")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovAmbiental.API.Models.RequisitoNorma", "Requisito")
                        .WithMany()
                        .HasForeignKey("RequisitoNormaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");

                    b.Navigation("Requisito");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.RequisitoNorma", b =>
                {
                    b.HasOne("GovAmbiental.API.Models.NormaAmbiental", "Norma")
                        .WithMany("Requisitos")
                        .HasForeignKey("NormaAmbientalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.Auditoria", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("NaoConformidades");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.NaoConformidade", b =>
                {
                    b.Navigation("AcaoCorretiva");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.NormaAmbiental", b =>
                {
                    b.Navigation("Requisitos");
                });

            modelBuilder.Entity("GovAmbiental.API.Models.RequisitoNorma", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
