apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ambiente de PRODUÇÃO
#   kubectl apply -k k8s/overlays/production
#   kubectl -n govambiental-prod rollout status deploy/govambiental-api
namespace: govambiental-prod

resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml
  - pdb.yaml

commonLabels:
  ambiente: producao

images:
  - name: ghcr.io/SEU-USUARIO/govambiental-api
    newTag: latest

patches:
  - path: patch-api.yaml
  - path: patch-ingress.yaml
  - path: patch-config.yaml
